### ISSUE TITLE
Allow drafts.

### ISSUE THREAD

**Issue by sidney-pham** [quadrupleslap/leven#13]
Don't render posts if filename ends with 'draft' or something.

**Comment by quadrupleslap** [comment]
Why would you need that?

**Comment by sidney-pham** [comment]
Really... I don't want people to see half finished blog posts and maybe I want to retract stupid blog posts (possibly concerning certain words in the English language) without deleting them entirely.

**Comment by sidney-pham** [comment]
In fact, your `Welcome, Stranger.md` post is a perfect post to make a draft. I'd want to be able to refer back to it, but not have it shown to the world.

**Comment by sidney-pham** [comment]
Wait a minute, I can totally just create a folder called `Drafts` or something in the blog root right? Pretty sure this solves the problem, just make it obvious to users.

**Comment by quadrupleslap** [comment]
How do you want to make it obvious?

**Comment by quadrupleslap** [comment]
Anyway, since it's a static site, nothing gets published until you build and then deploy, so this issue seems irrelevant, so closing.
