### ISSUE TITLE
Add tag functionality.

### ISSUE THREAD

**Issue by sidney-pham** [quadrupleslap/leven#15]
Is this even possible with a static site?

**Comment by quadrupleslap** [comment]
Yeah, it's possible (like Hugo's taxonomies), but how could you define the tags for a post without adding frontmatter? Sounds like too much friction.

**Comment by quadrupleslap** [comment]
(Reopen if you still think tags are useful, because ctrl+f on the archive page and/or custom DDG search seem to be superior in every way.)
