### ISSUE TITLE
Add content.summary

### ISSUE THREAD

**Issue by krircc** [quadrupleslap/leven#20]
at index.html, now show the whole content in each blog, it's too much content for read. usually should show the each blog's content.summary.

**Comment by quadrupleslap** [comment]
Sure! What should the summary be defined as, though? The main concerns are the length of the summary and the fact that the post is in Markdown.

**Comment by krircc** [comment]
@quadrupleslap   I think 3 line , maybe  usually The first 150 character in that blog's content . is that well ?
i think it's my word's wrong. it should't be content.summary.

**Comment by quadrupleslap** [comment]
And it's okay if the excerpt contains things like headings? Edit: Nevermind, if someone wants to edit those they can use CSS styles to un-heading-ify the headings.

**Comment by krircc** [comment]
@quadrupleslap  thanks

**Comment by krircc** [comment]
@quadrupleslap it should be another 'posts' dir in 'out', that content's blogs should be there. is that ok?
i can send a PR for this.

**Comment by krircc** [comment]
I think it should close now
